#!/bin/bash
echo "FAST Feature Detection / Provides libFast.a / Author : Edward Rosten http://www.edwardrosten.com/work/fast.html"  

rm libFast.a

gcc -Os -O3 -fexpensive-optimizations -c fast.c -o fast.o
gcc -Os -O3 -fexpensive-optimizations -c fast_9.c -o fast_9.o 
gcc -Os -O3 -fexpensive-optimizations -c nonmax.c -o nonmax.o

ar  rcs libFast.a fast.o fast_9.o nonmax.o

rm fast.o fast_9.o nonmax.o
  
if [ -e libFast.a ]
then
  echo "Success.."
else
  echo "Failure.."
fi


exit 0
