#!/bin/bash
echo "RoboVision WxWidgets GUI / Provides the main executable / Author : Ammar Qammaz"  

OUTPUT="robovisionx"

if [ -e $OUTPUT ]
then
  rm $OUTPUT
fi

CFLAGS="-s -O3 -fexpensive-optimizations"

OURLIBRARIES="../RoboKernel/libRoboKernel.a ../VideoInput/libVideoInput.a ../VisualCortex/libVisualCortex.a ../InputParser/libInputParser_C.a ../MotorFoundation/libMotorHAL.a ../MotorFoundation/MD23/libMD23.a ../MotorFoundation/Arduino/libRoboVisionSensorLib.a ../WorldMapping/MasterpathPlanning/libMasterpathPlanning.a ../WorldMapping/MasterWorld/libMasterWorld.a ../RVKnowledgeBase/libRVKnowledgeBase.a ../3dpartylibs/fast/libFast.a"


OPENCVSTUFF="`pkg-config --cflags --libs opencv`"
WXWIDGETSSTUFF="`wx-config --libs` `wx-config --cflags`"
LIBRARIES="-pthread -lgsl -lpng -lgslcblas -lm -lrt"


g++ RoboVisionXApp.cpp RoboVisionXMain.cpp MapOverview.cpp FramesOSD.cpp  FeedScreenMemory.cpp CortexSettings.cpp RememberImage.cpp $CFLAGS  $OURLIBRARIES  $WXWIDGETSSTUFF $OPENCVSTUFF  -L.  $LIBRARIES -o $OUTPUT

cd memfs/calibration
./make
cd ../..

if [ -e $OUTPUT ]
then
  echo "Success.."
else
  echo "Failure.."
fi

exit 0
