#!/bin/bash
echo "RoboVision WxWidgets GUI / Provides the main executable / Author : Ammar Qammaz"  

if [ -e bin/Release/RoboVisionX ]
then
  rm bin/Release/RoboVisionX
fi

g++ RoboVisionXApp.cpp RoboVisionXApp.h RoboVisionXMain.cpp RoboVisionXMain.h FramesOSD.cpp FramesOSD.h  FeedScreenMemory.cpp FeedScreenMemory.h CortexSettings.cpp CortexSettings.h  RememberImage.cpp RememberImage.h  ../RoboKernel/libRoboKernel.a ../VideoInput/libVideoInput.a ../VisualCortex/libVisualCortex.a ../InputParser/libInputParser_C.a ../MotorFoundation/libMotorHAL.a ../MotorFoundation/MD23/libMD23.a ../MotorFoundation/Arduino/libRoboVisionSensorLib.a ../WorldMapping/MasterpathPlanning/libMasterpathPlanning.a ../WorldMapping/MasterWorld/libMasterWorld.a ../RVKnowledgeBase/libRVKnowledgeBase.a ../3dpartylibs/fast/libFast.a `wx-config --libs` `wx-config --cxxflags` `pkg-config --cflags --libs opencv` -L. -pthread -lgsl -lpng -lgslcblas -lm -o bin/Release/RoboVisionX

cd memfs/calibration
./make
cd ../..

if [ -e bin/Release/RoboVisionX ]
then
  echo "Success.."
else
  echo "Failure.."
fi

exit 0
