#!/bin/sh

if [ -e /usr/lib/libv4l/v4l2convert.so ]
then
  LD_PRELOAD=/usr/lib/libv4l/v4l2convert.so  ./bin/Release/RoboVisionX
fi

if [ -e /usr/lib32/libv4l/v4l2convert.so ]
then
  LD_PRELOAD=/usr/lib32/libv4l/v4l2convert.so  ./bin/Release/RoboVisionX
fi


if [ -e /usr/lib/i386-linux-gnu/libv4l/v4l2convert.so ]
then
  LD_PRELOAD=/usr/lib/i386-linux-gnu/libv4l/v4l2convert.so  ./bin/Release/RoboVisionX
fi

exit 0

#LD_PRELOAD=/usr/lib32/libv4l/v4l1compat.so
