#!/bin/bash
g++ `pkg-config --cflags --libs opencv` my_main.c ../libVisualCortex.a ../../3dpartylibs/fast/libFast.a ../../WorldMapping/MasterWorld/libMasterWorld.a -L.  -lgsl -lgslcblas -s -O3 -o stereo_disparity_my_tester
g++ `pkg-config --cflags --libs opencv` opencv_main.cpp  -L. -s -O3 -o stereo_disparity_opencv_tester
exit 0
