#!/bin/bash
gcc my_main.c  ../libVisualCortex.a ../../3dpartylibs/fast/libFast.a ../../WorldMapping/MasterWorld/libMasterWorld.a `pkg-config --cflags --libs opencv` -L.  -pthread -lgsl -lpng -ljpeg -lgslcblas -lm -lrt -s -O3 -o stereo_disparity_my_tester
g++  opencv_main.cpp  `pkg-config --cflags --libs opencv` -L.  -lm -lrt -s -O3 -o stereo_disparity_opencv_tester
exit 0
