#!/bin/bash
echo "MotorFoundation  / Provides libMotorHAL.a  / Author : Ammar Qammaz"   


echo "Compiling Mindstorm Libs.."
cd Mindstorm
./make
cd ..

echo "Compiling MD23-MD25 Libs.."
cd MD23
./make
cd ..

echo "Compiling Arduino Libs.."
cd Arduino
./make
cd ..


if [ -e libMotorHAL.a ]
then
  rm libMotorHAL.a
fi  


gcc -c MotorHAL.c -o MotorHAL.o 

ar  rcs libMotorHAL.a MotorHAL.o  

rm MotorHAL.o 


if [ -e libMotorHAL.a ]
then
  echo "Success.."
else
  echo "Failure.."
fi

exit 0
