#!/bin/bash 
echo "Copying RoboVision To Runtime Directory.."
sudo ./Scripts/init_memory_runtime.sh

echo "Copying Things inside runtime Directory.."
sudo ./Scripts/memoryfs_prepare.sh

echo "Running RoboVision From Runtime Directory.."

touch RoboVisionRuntime/test_file
if [ -e RoboVisionRuntime/test_file ]
then
  echo "RoboVisionRuntime Space is OK .."  
  rm RoboVisionRuntime/test_file
else
  echo "RoboVisionRuntime was not allocated by Scripts/init_memory_runtime.sh, everything will fail :P , check it" > error_message.txt 
fi

cd RoboVisionRuntime
echo "Starting GuarddoG (TM ;P).."
sudo ./RoboVisionCLICompat
echo "GuarddoG has stopped , cleaning up .."
cd ..

killall RoboVisionCLI
killall RoboVisionCLICompat

sleep 5

sudo ./Scripts/close_memory_runtime.sh
echo "GuarddoG Init Service is Done.."
exit 0
