#!/bin/bash 
echo "Copying RoboVision To Runtime Directory.."
sudo ./Scripts/Startup/init_memory_runtime.sh

echo "Copying Things inside runtime Directory.."
sudo ./Scripts/Startup/memoryfs_prepare.sh

echo "Starting SMS Receiver.."
sudo ./Scripts/Startup/startSMSReceiver

echo "Running RoboVision From Runtime Directory.."

touch RoboVisionRuntime/test_file
if [ -e RoboVisionRuntime/test_file ]
then
  echo "RoboVisionRuntime Space is OK .."  
  rm RoboVisionRuntime/test_file
else
  echo "RoboVisionRuntime was not allocated by Scripts/init_memory_runtime.sh, everything will fail :P , check it" > error_message.txt 
fi

cd RoboVisionRuntime
echo "Starting GuarddoG (TM ;P).."
sudo ./RoboVisionCLICompat noinput
echo "GuarddoG has stopped , cleaning up .."
cd ..

sudo killall RoboVisionCLI
sudo killall RoboVisionCLICompat
sudo killall gsmsmsd

sleep 5

sudo ./Scripts/Startup/close_memory_runtime.sh
echo "GuarddoG Init Service is Done.."
exit 0
