#!/bin/bash
echo "Arduino ATMEL Library  / Provides libRoboVisionSensorLib.a  / Author : Ammar Qammaz"    


if [ -e libRoboVisionSensorLib.a ]
then
  rm libRoboVisionSensorLib.a
fi  

rm .a

gcc -c main.c -o main.o 
gcc -c arduino_serial.c -o arduino_serial.o 


echo "Linking files.."
ar  rcs libRoboVisionSensorLib.a main.o arduino_serial.o  

echo "Cleaning compiled object files.."
rm main.o arduino_serial.o 

cd RoboVisionSensorTester
./make
cd ..


if [ -e libRoboVisionSensorLib.a ]
then
  echo "Success.."
else
  echo "Failure.."
fi


