#!/bin/bash
echo "Hand made make script for VisualCortex - VisualCortex_Tester .."
echo "Should provide libVisualCortex.a and VisCortx_Tester/bin/Release/VisCortx_Tester"
echo "Written by Ammar Qammaz a.k.a AmmarkoV :) "
echo "Compiling files.."
gcc -c DisparityDepthMap.c -o DisparityDepthMap.o
gcc -c MovementRegistration.c -o MovementRegistration.o
gcc -c FeatureExtraction.c -o FeatureExtraction.o 
gcc -c FeatureTracking.c -o FeatureTracking.o
gcc -c PatternRecognition.c -o PatternRecognition.o
gcc -c Precalculations.c -o Precalculations.o 
gcc -c StateSetting.c -o StateSetting.o
gcc -c VisCortexFilters.c -o VisCortexFilters.o
gcc -c VisionMemory.c -o VisionMemory.o 
gcc -c VisualCortex.c -o VisualCortex.o


echo "Linking files.."
ar  rcs libVisualCortex.a DisparityDepthMap.o MovementRegistration.o FeatureExtraction.o PatternRecognition.o FeatureTracking.o Precalculations.o StateSetting.o VisCortexFilters.o VisionMemory.o VisualCortex.o

echo "Cleaning compiled object files.."
rm DisparityDepthMap.o MovementRegistration.o FeatureExtraction.o PatternRecognition.o FeatureTracking.o Precalculations.o StateSetting.o VisCortexFilters.o VisionMemory.o VisualCortex.o

echo "Compiling Tester.."
cd VisCortx_Tester
./make
cd ..

echo "Done.."
exit 0
