#include "VisCortexOptimizedConvolutionFilters.h"
#include "VisCortexConvolutionFilters.h"
#include "VisCortexFilters.h"
#include "Precalculations.h"
#include "FeatureTracking.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>




//THIS CODE IS AUTO GENERATED BY  OptimizedCodeGenerator! ! !



int ConvolutionFilter9_1ByteOptimized(struct VideoRegister * monochrome_reg,struct VideoRegister * target_reg,signed char * table,signed int divisor)
{  // FALLBACK TO NOT OPTIMIZED CONVOLUTION FILTER 
 return ConvolutionFilter9_1Byte(monochrome_reg,target_reg,table,divisor);
}

int ConvolutionFilter9_3ByteOptimized(struct VideoRegister * rgb_reg,struct VideoRegister * target_reg,signed char * table,signed int divisor)
{  // FALLBACK TO NOT OPTIMIZED CONVOLUTION FILTER 
 return ConvolutionFilter9_3Byte(rgb_reg,target_reg,table,divisor);
}
int ConvolutionFilter9_AutoByteOptimized(struct VideoRegister * rgb_reg,struct VideoRegister * target_reg,signed char * table,signed int divisor)
{  // FALLBACK TO NOT OPTIMIZED CONVOLUTION FILTER 
  if ( rgb_reg->depth == 1 ) { return ConvolutionFilter9_1ByteOptimized(rgb_reg,target_reg,table,divisor); } else
  if ( rgb_reg->depth == 3 ) { return ConvolutionFilter9_3ByteOptimized(rgb_reg,target_reg,table,divisor); }
  fprintf(stderr,"This color depth ( %u ) doesnt have a convolution filter implemented \n",rgb_reg->depth); return 0;
}

