#include "VisCortexOptimizedConvolutionFilters.h"
#include "VisCortexConvolutionFilters.h"
#include "VisCortexFilters.h"
#include "Precalculations.h"
#include "FeatureTracking.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>




//THIS CODE IS AUTO GENERATED BY  OptimizedCodeGenerator! ! !



int ConvolutionFilter9_1ByteOptimized(unsigned int monochrome_reg,unsigned int target_reg,signed char * table,signed int divisor)
{  // FALLBACK TO NOT OPTIMIZED CONVOLUTION FILTER
 return ConvolutionFilter9_1Byte(monochrome_reg,target_reg,table,divisor);
}

int ConvolutionFilter9_3ByteOptimized(unsigned int rgb_reg,unsigned int target_reg,signed char * table,signed int divisor)
{  // FALLBACK TO NOT OPTIMIZED CONVOLUTION FILTER
 return ConvolutionFilter9_3Byte(rgb_reg,target_reg,table,divisor);
}

