#!/bin/bash
echo "MasterPathPlanning and its tester / Provides libMasterpathPlanning.a / Author : Ammar Qammaz"  

rm libMasterpathPlanning.a 

gcc -c main.c -o main.o
gcc -c PathPlanningCore.c -o PathPlanningCore.o
gcc -c PathPlanningHelper.c -o PathPlanningHelper.o
gcc -c NormalizePath.c -o NormalizePath.o
gcc -c LogoHighLevelPath.c -o LogoHighLevelPath.o 
gcc -c WorldLocations.c -o WorldLocations.o 

echo "Linking files.."
ar  rcs libMasterpathPlanning.a main.o PathPlanningCore.o PathPlanningHelper.o NormalizePath.o LogoHighLevelPath.o WorldLocations.o 

echo "Cleaning compiled object files.."
rm main.o PathPlanningCore.o PathPlanningHelper.o NormalizePath.o LogoHighLevelPath.o WorldLocations.o

echo "Compiling Tester.."
cd MasterpathPlanning_Tester
./make
cd ..

if [ -e libMasterpathPlanning.a ]
then
  echo "Success.."
else
  echo "Failure.."
fi


exit 0
