#!/bin/bash

echo "Compiling 3d party libraries"


if [ -d "OpenKinect" ]; then
cd OpenKinect 
./make
cd ..
else
  echo "Error : Could not find OpenKinect lib directory" 
fi

if [ -d "OpenSURFcpp" ]; then
cd OpenSURFcpp
./make
cd ..
else
  echo "Error : Could not find OpenSURFcpp lib directory" 
fi

if [ -d "fast" ]; then
cd fast
./make
cd ..
else
  echo "Error : Could not find fast lib directory" 
fi

if [ -d "libelas" ]; then
cd libelas
./make
cd ..
else
  echo "Error : Could not find libelas lib directory" 
fi


echo "Done"



exit 0
