#!/bin/bash
echo "Trying to Compile LibElas http://www.rainsoft.de/software/libelas.html "
echo "Author: Andreas Geiger"

if [ -e build/elas ]
then
  echo "libELAS Executable seems to exist ..  Skipping make operation , since this file rarely changes..! " 
 cd ..
 exit 0
fi


mkdir build
echo "Cleaning everything"
rm -fr build/*

echo "Recompiling.."
cd build
cmake ..
make

if [ -e elas ]
then
  echo "libELAS Executable is OK .."
  echo "Copying it to VisualCortex Tester .."
  cp elas ../../../VisualCortex/DisparityMapComparison/elas
else
  echo "libELAS Executable compilation FAILED !!!!!!!!!!" 
fi


cd ..
echo "Done"
exit 0
