#!/bin/bash

if [ -e bin/Release/ircbot ]
then
  echo "Starting IRC Bot"
else
  echo "Cannot Find IRC Bot executable"
  exit 1
fi 

bin/Release/ircbot GuarddoG irc.freenode.org 6667 127.0.0.1 6667 names >> log&
sleep 3
commands/join 127.0.0.1 6667 foss-aueb
echo "Success"

exit 0
