#!/bin/bash
echo "Hand made make script for RVKnowledgeBase placer .."
echo "Should provide libRVKnowledgeBase.a"
echo "Written by Ammar Qammaz a.k.a AmmarkoV :) "
echo "Compiling files.."
gcc -c RVKnowledgeBase.c -o RVKnowledgeBase.o 

echo "Linking files.."
ar  rcs libRVKnowledgeBase.a RVKnowledgeBase.o 

echo "Cleaning compiled object files.."
rm RVKnowledgeBase.o 
 
echo "Done.."
exit 0
