#!/bin/bash
echo "RVKnowledgeBase and its tester / Provides libRVKnowledgeBase.a / Author : Ammar Qammaz"   


if [ -e libRVKnowledgeBase.a ]
then
  rm libRVKnowledgeBase.a
fi  

gcc -c RVKnowledgeBase.c -o RVKnowledgeBase.o 
gcc -c StringList.c -o StringList.o 

ar  rcs libRVKnowledgeBase.a RVKnowledgeBase.o StringList.o


rm RVKnowledgeBase.o StringList.o
 

if [ -e libRVKnowledgeBase.a ]
then
  echo "Success.."
else
  echo "Failure.."
fi

exit 0
