#!/bin/bash
if [ $# -lt 4 ]
then
  echo "Usage: `basename $0` ircd_host_ip ircd_port channel_name(without #) \"Message goes here\" "
  echo "i.e. : `basename $0` 127.0.0.1 6667 my_irc_channel \"Hello World\" "
  exit $E_BADARGS
fi

echo ';PRIVMSG' '#'$3' : '$4 | nc $1 $2

exit 0 
