#!/bin/bash
echo "Hand made make script for RoboVisionX binary .."
echo "Should provide bin/Release/InternetVideoTransmission " 
echo "Compiling files.."
g++ InternetVideoTransmissionApp.cpp InternetVideoTransmissionApp.h InternetVideoTransmissionMain.cpp InternetVideoTransmissionMain.h network_framework.cpp network_framework.h  ../libVideoInput.a `wx-config --libs` `wx-config --cxxflags` -L. -pthread -lpng -o bin/Release/InternetVideoTransmission


echo "Done.."
exit 0
