#!/bin/bash
echo "MD23 Motors Lib  / Provides libMD23.a  / Author : Ammar Qammaz"   

rm libMD23.a

gcc -c MD23.c -o MD23.o 
gcc -c MD23_commands.c -o MD23_commands.o 
gcc -c usb_2_i2c.c -o usb_2_i2c.o 

ar  rcs libMD23.a MD23.o MD23_commands.o usb_2_i2c.o  

rm MD23.o MD23_commands.o usb_2_i2c.o

cd MD23_Tester
./make
cd ..

if [ -e libMD23.a ]
then
  echo "Success.."
else
  echo "Failure.."
fi

