#!/bin/bash

STARTDIR=`pwd`
 
cd ../IRCInterface
cd IRCInterface

if [ -e bin/Release/ircbot ]
then
  echo "Starting IRC Bot"
else
  echo "Cannot Find IRC Bot executable"
  exit 1
fi 
 
bin/Release/ircbot GuarddoG irc.freenode.org 6667 127.0.0.1 6667 names >> log

echo "going back to $STARTDIR "

BOT_OK = `ps -A | grep ircbot | wc -l`
echo "Trying to find out if bot process ok = $BOT_OK"

cd $STARTDIR
exit 0
