#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void WriteHeader()
{
    FILE *hofp;
    hofp = fopen("VisCortexOptimizedConvolutionFilters.h", "w");
    if (hofp == 0)
     {
      fprintf(stderr, "Can't open header file \n");
      exit(1);
     } else
     {
        fprintf(hofp,"#ifndef VISCORTEXCONVOLUTIONFILTERSOPTIMIZED_H_INCLUDED\n");
        fprintf(hofp,"#define VISCORTEXCONVOLUTIONFILTERSOPTIMIZED_H_INCLUDED\n");

        fprintf(hofp,"int ConvolutionFilter9_1ByteOptimized(unsigned int monochrome_reg,unsigned int target_reg,signed char * table,signed int divisor);\n");
        fprintf(hofp,"int ConvolutionFilter9_3ByteOptimized(unsigned int rgb_reg,unsigned int target_reg,signed char * table);\n");

        fprintf(hofp,"#endif // CONVOLUTIONFILTERS_H_INCLUDED\n");
        fprintf(hofp,"\n\n");

        fclose(hofp);
     }

}

void StartCBody(FILE *ofp)
{
   fprintf(ofp,"#include \"VisCortexOptimizedConvolutionFilters.h\"\n");
   fprintf(ofp,"#include \"VisCortexConvolutionFilters.h\"\n");
   fprintf(ofp,"#include \"VisCortexFilters.h\"\n");
   fprintf(ofp,"#include \"Precalculations.h\"\n");
   fprintf(ofp,"#include \"FeatureTracking.h\"\n");
   fprintf(ofp,"#include <stdlib.h>\n");
   fprintf(ofp,"#include <stdio.h>\n");
   fprintf(ofp,"#include <string.h>\n");
   fprintf(ofp,"\n\n\n\n");
   fprintf(ofp,"//THIS CODE IS AUTO GENERATED BY  OptimizedCodeGenerator! ! !");
   fprintf(ofp,"\n\n\n\n");


}

void EndCBody(FILE *ofp)
{
   fprintf(ofp,"\n");
}



void UnrollConvolution9_1Byte(FILE *ofp,int x_unroll)
{
   fprintf(ofp,"int ConvolutionFilter9_1ByteOptimized(unsigned int monochrome_reg,unsigned int target_reg,signed char * table,signed int divisor)\n");
   fprintf(ofp,"{\n\n");


   fprintf(ofp,"if (!ThisIsA1ByteRegister(monochrome_reg)) { return 0; }\n");
   fprintf(ofp,"video_register[target_reg].depth=1;\n");
   fprintf(ofp,"// 3 x 3 = 9 :P\n");
   fprintf(ofp,"unsigned char * out_px=video_register[target_reg].pixels;\n");
   fprintf(ofp,"unsigned char * cur_px=video_register[monochrome_reg].pixels;\n");
   fprintf(ofp,"unsigned char * px=video_register[monochrome_reg].pixels;\n");
   fprintf(ofp,"\n");
   fprintf(ofp,"if ( divisor == 0 ) { divisor = 1; }\n");
   fprintf(ofp,"signed int cur_value ;\n");
   fprintf(ofp,"unsigned int x=1,y=1;\n");
   fprintf(ofp,"\n");
   fprintf(ofp,"cur_px += metrics[RESOLUTION_X];\n");
   fprintf(ofp,"out_px += metrics[RESOLUTION_X];\n");



   fprintf(ofp," while ( y < video_register[monochrome_reg].size_y-1 )\n");
   fprintf(ofp,"  {\n");
   fprintf(ofp,"      x=1;\n");
   fprintf(ofp,"     ++cur_px;\n");
   fprintf(ofp,"     ++out_px;\n");

   int x=0;
   while ( x<x_unroll-1)
     {
          fprintf(ofp,"px = cur_px - metrics[RESOLUTION_X];\n");
          fprintf(ofp,"cur_value   = (signed int) *px * table[0]; ++px; cur_value  += (signed int) *px * table[1]; ++px; cur_value  += (signed int) *px * table[2]; ++px;\n");

          fprintf(ofp,"px += metrics[RESOLUTION_X]-3;\n");
          fprintf(ofp,"cur_value  += (signed int) *px * table[5]; --px; cur_value  += (signed int) *px * table[4]; --px; cur_value  += (signed int) *px * table[3]; --px;\n");

          fprintf(ofp,"px += metrics[RESOLUTION_X]-3;\n");
          fprintf(ofp,"cur_value  += (signed int) *px * table[6]; ++px; cur_value  += (signed int) *px * table[7]; ++px; cur_value  += (signed int) *px * table[8]; ++px;\n");

          fprintf(ofp,"cur_value = (signed int) cur_value / divisor;\n");
          fprintf(ofp,"px = px - metrics[RESOLUTION_X] - 2;\n");

          fprintf(ofp,"if ( cur_value < 0   ) { *out_px=0; } else\n");
          fprintf(ofp,"if ( cur_value > 255 ) { *out_px=255; } else\n");
          fprintf(ofp,"                       { *out_px=(unsigned char) cur_value; }\n");

          fprintf(ofp,"++out_px;\n");
          fprintf(ofp,"++cur_px;\n");

         ++x;
     }

fprintf(ofp,"          out_px+=1; \n");
fprintf(ofp,"          cur_px+=1; \n");
fprintf(ofp,"\n");
fprintf(ofp,"        ++y;\n");
fprintf(ofp,"     }\n");
fprintf(ofp,"return 1;\n");
fprintf(ofp,"}\n");
}


void UnrollConvolution9_3Byte(FILE *ofp,int x_unroll)
{
   fprintf(ofp,"int ConvolutionFilter9_3ByteOptimized(unsigned int rgb_reg,unsigned int target_reg,signed char * table)\n");
   fprintf(ofp,"{  // FALLBACK TO NOT OPTIMIZED CONVOLUTION FILTER \n");
   fprintf(ofp," return ConvolutionFilter9_3Byte(rgb_reg,target_reg,table);\n");
   fprintf(ofp,"}\n");
}



void DefaultNotOptimizedOutput(FILE *ofp)
{
   StartCBody(ofp);

   fprintf(ofp,"int ConvolutionFilter9_1ByteOptimized(unsigned int monochrome_reg,unsigned int target_reg,signed char * table,signed int divisor)\n");
   fprintf(ofp,"{  // FALLBACK TO NOT OPTIMIZED CONVOLUTION FILTER \n");
   fprintf(ofp," return ConvolutionFilter9_1Byte(monochrome_reg,target_reg,table,divisor);\n");
   fprintf(ofp,"}\n\n");

   fprintf(ofp,"int ConvolutionFilter9_3ByteOptimized(unsigned int rgb_reg,unsigned int target_reg,signed char * table)\n");
   fprintf(ofp,"{  // FALLBACK TO NOT OPTIMIZED CONVOLUTION FILTER \n");
   fprintf(ofp," return ConvolutionFilter9_3Byte(rgb_reg,target_reg,table);\n");
   fprintf(ofp,"}\n");

   EndCBody(ofp);
}



void OptimizedOutput(FILE *ofp)
{
        StartCBody(ofp);
        UnrollConvolution9_1Byte(ofp,320);
        UnrollConvolution9_3Byte(ofp,320);
        EndCBody(ofp);
}

int main(int argc, char **argv)
{

    FILE *ofp;

    ofp = fopen("VisCortexOptimizedConvolutionFilters.c", "w");

   if (ofp == 0)
    {
      fprintf(stderr, "Can't open output file \n");
      exit(1);
    } else
    {


        if ( argc > 1 )
          {
            if (strcmp(argv[1],"optimize")==0)
                              {
                                 fprintf(stderr,"Optimizing Output..!\n");
                                 WriteHeader();
                                 OptimizedOutput(ofp);
                              } else
            if (strcmp(argv[1],"default")==0)
                              {
                                 fprintf(stderr,"Default Output..!\n");
                                 WriteHeader();
                                 DefaultNotOptimizedOutput(ofp);
                              } else
                              {
                                  fprintf(stderr,"Unknown flag\n");
                              }

          } else
          {
               fprintf(stderr,"Please call this program with one of the following flags ( optimize , default )\n");
          }



        fclose(ofp);
    }


    return 0;
}
