#!/bin/sh  
echo RoboVisionCLICompat parameter is $1

BINFOLDERPATH="."
BINPATH="robovision"
PARAMS="$@"
VALGRIND="valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes  --track-origins=yes"
SAVETOFILE=" "


echo "starting $BINPATH with parameters $PARAMS"

if [ -e /usr/lib/x86_64-linux-gnu/libv4l/v4l2convert.so ]
then
  LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libv4l/v4l2convert.so $VALGRIND $BINFOLDERPATH/$BINPATH $PARAMS $SAVETOFILE
  exit 0
fi

if [ -e /usr/lib/libv4l/v4l2convert.so ]
then
  LD_PRELOAD=/usr/lib/libv4l/v4l2convert.so $VALGRIND $BINFOLDERPATH/$BINPATH $PARAMS $SAVETOFILE
  exit 0
fi

if [ -e /usr/lib32/libv4l/v4l2convert.so ]
then
  LD_PRELOAD=/usr/lib32/libv4l/v4l2convert.so $VALGRIND $BINFOLDERPATH/$BINPATH $PARAMS $SAVETOFILE
  exit 0
fi

if [ -e /usr/lib/i386-linux-gnu/libv4l/v4l2convert.so ]
then
  LD_PRELOAD=/usr/lib/i386-linux-gnu/libv4l/v4l2convert.so $VALGRIND $BINFOLDERPATH/$BINPATH $PARAMS $SAVETOFILE
  exit 0
fi
 
echo "Oh no.. they must have changed filenames again .. or you are running this script in an untested distro.." 
echo "Trying one last trick to preload v4l2convert.so.. Please also make sure you run the apt-get-dependencies script..!" 

CUSTOM_PLACE=`sudo find /usr -name v4l2convert.so  | grep v4l2convert`

if [ -e "$CUSTOM_PLACE" ]
then
  LD_PRELOAD=$CUSTOM_PLACE $VALGRIND $BINFOLDERPATH/$BINPATH $PARAMS $SAVETOFILE
  exit 0
fi

exit 0
