#!/bin/bash
echo "RoboVisionCLI  / Provides Headless Lite Executable  / Author : Ammar Qammaz"  

OUTPUT="robovision"

if [ -e $OUTPUT ]
then
  rm $OUTPUT
fi 

CFLAGS="-s -O3 -fexpensive-optimizations"

OURLIBRARIES="../RoboKernel/libRoboKernel.a ../VideoInput/libVideoInput.a ../VisualCortex/libVisualCortex.a ../AmmarServer/src/AmmServerlib/libAmmarServer.a ../InputParser/libInputParser_C.a ../MotorFoundation/libMotorHAL.a ../MotorFoundation/MD23/libMD23.a ../MotorFoundation/Arduino/libRoboVisionSensorLib.a ../WorldMapping/MasterpathPlanning/libMasterpathPlanning.a ../WorldMapping/MasterWorld/libMasterWorld.a ../RVKnowledgeBase/libRVKnowledgeBase.a ../3dpartylibs/fast/libFast.a"

OPENCVSTUFF="`pkg-config --cflags --libs opencv`"

LIBRARIES="-pthread -lgsl -lpng -ljpeg -lgslcblas -lm -lrt"

g++ main.cpp $OURLIBRARIES $OPENCVSTUFF -L. $LIBRARIES -o $OUTPUT


if [ -e $OUTPUT ]
then
  echo "Success.."
else
  echo "Failure.."
fi

exit 0
