#!/bin/bash
echo "InputParser and its tester / Provides libInputParser.a / Author : Ammar Qammaz" 

rm libInputParser_C.a 

gcc -c InputParser_C.c -o InputParser_C.o 

ar  rcs libInputParser_C.a InputParser_C.o

rm InputParser_C.o 

if [ -e libInputParser_C.a ]
then
  echo "Success.."
else
  echo "Failure.."
fi

exit 0
