#!/bin/bash
echo "Hand made make script for InputParser - InputParser_C_Tester .."
echo "Should provide libInputParser.a  "
echo "Written by Ammar Qammaz a.k.a AmmarkoV :) "
echo "Compiling files.."  
gcc -c InputParser_C.c -o InputParser_C.o 

echo "Linking files.." 
ar  rcs libInputParser_C.a InputParser_C.o

echo "Cleaning compiled object files.."
rm InputParser_C.o 

echo "Done.."
exit 0
