#! /bin/sh
# /etc/init.d/blah
#

# Some things that run always
# i.e. touch /var/lock/blah

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting GuarddoG script "
      cd /home/guarddog/RoboVision/
  
      sudo ./Scripts/StopProcessesThatAreNotNeeded 

      #make sure wifi is ok!
      sudo ./Scripts/MadWifiAPRestart

      #make sure wifi is ok!
      sudo ./Scripts/PlaySound  "./DataSets/Sounds/startupv.wav"
      
      #use ethernet as gateway :P ( or else no network connectivity )  
      route add default gw 192.168.1.1 eth0

      #startup guarddog!
      sudo ./guarddog_init_service&
    ;;
  stop)
    echo "Stopping GuarddoG script" 
       cd /home/guarddog/RoboVision/
       sudo ./Scripts/PlaySound  "./DataSets/Sounds/shutdownv.wav"

       sudo killall guarddog_init_service
       sudo killall RoboVisionCLI
       sudo killall RoboVisionX
    ;;
  *)
    echo "Usage: /etc/init.d/guarddog_linux_startup_script {start|stop}"
    exit 1
    ;;
esac

exit 0 
