#!/bin/bash


CUDA_PATH="/usr/local/cuda-5.0"
CUDA_INC_PATH="$CUDA_PATH/include"
CUDA_BIN_PATH="$CUDA_PATH/bin"


# Common includes and paths for CUDA
INCLUDES="-I$CUDA_INC_PATH -I."

nvcc $INCLUDES sat.cu -o testSAT
nvcc $INCLUDES sat.cu -lib -o SATlib.a

exit 0