#!/bin/bash

cd MasterpathPlanning
./make
cd ..

g++ WorldMappingApp.cpp WorldMappingMain.cpp MasterpathPlanning/libMasterpathPlanning.a ../MotorFoundation/libMotorHAL.a ../MotorFoundation/MD23/libMD23.a `wx-config --libs` `wx-config --cxxflags` -L. -o bin/Release/WorldMapping
exit 0
