#!/bin/bash
gcc main.c ../3dpartylibs/OpenKinect/wrappers/c_sync/libfreenect_sync.c ../3dpartylibs/OpenKinect/build/lib/libfreenect.a ../3dpartylibs/OpenKinect/build/lib/libfreenect_sync.a -lusb-1.0 -L. -pthread -lrt -o test
exit 0
