#!/bin/bash
gcc test.c libfreenect_sync.c ../3dpartylibs/OpenKinect/build/lib/libfreenect.a ../3dpartylibs/OpenKinect/build/lib/libfreenect_sync.a -lglut -lGL -lGLU -lXxf86vm -lusb-1.0 -ggdb `pkg-config opencv --cflags --libs` -L. -pthread -lrt -o test
exit 0
